name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "ver/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    permissions:
      contents: write
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"

      - name: Apply Patches
        run: ./gradlew applyAllPatches --stacktrace

      - name: Create MojmapPaperclipJar
        if: "contains(github.event.commits[0].message, '[release]')"
        run: ./gradlew createMojmapPaperclipJar --stacktrace

      - name: Prepare release notes and artifacts
        if: "contains(github.event.commits[0].message, '[release]')"
        run: |
          chmod +x ./scripts/prepareRelease.sh
          ./scripts/prepareRelease.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}

      - name: Upload Jellyfish
        if: "contains(github.event.commits[0].message, '[release]')"
        uses: actions/upload-artifact@main
        with:
          name: Jellyfish 1.21.6
          path: ./jellyfish-server/build/libs/jellyfish-paperclip-1.21.6-R0.1-SNAPSHOT-mojmap.jar

      - name: Release Jellyfish
        if: "contains(github.event.commits[0].message, '[release]')"
        uses: softprops/action-gh-release@master
        with:
          name: "🪼 Jellyfish build ${{ env.BUILD_NUMBER }}"
          tag_name: "ver-1.21.6"
          files: |
            ./jellyfish-server/build/libs/jellyfish-paperclip-1.21.6-R0.1-SNAPSHOT-mojmap.jar
            ./jellyfish-api/build/libs/jellyfish-api-1.21.6-R0.1-SNAPSHOT.jar
          body_path: "./RELEASE.md"
          token: "${{ secrets.GITHUB_TOKEN }}"
          target_commitish: "${{ github.sha }}"
          draft: false
          prerelease: false
